### PR TITLE
Map

### PR DESCRIPTION
**Pull request by jsheng112**
created a new tap with a map. There are simple event listeners so that when you click on the map it will show up as a marker, and the markers are labeled alphabetically.

### CODE REVIEW

**Review by meltsufin — APPROVED** [review]
Looks good! I guess it's mostly for fun because I'm not sure what the practical use of clicking on the map and creating alphabetical markers would be. :)

**Comment by jsheng112** [comment]
@meltsufin Yeah it was mostly just an exercise to see how Maps works, but I didn't have any good ideas about how to use it in the portfolio.

**Review by elefeint — APPROVED** [review]
You'll bet I got to "Z" when testing to check what happens!

Mike -- you are not seeing the possibilities here. This map on a touchscreen device can occupy a 2-4 year old for at least a half hour.

**Comment by meltsufin** [comment]
> Mike -- you are not seeing the possibilities here. This map on a touchscreen device can occupy a 2-4 year old for at least a half hour.

Haha, I'll give it a try!

**Pull request merged**
